import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { RawMaterial } from '../raw-materials/raw-material.entity';
import { MaterialBatch } from '../material-batches/material-batch.entity';

// One row per (consumption event, batch drawn from) pair -- generated by
// MaterialConsumptionsService.recordConsumption, not hand-created, because a
// single "use 10kg of wood" request can span more than one batch (FIFO).
// unitCost/totalCost are a snapshot of the batch's price at draw time.
@Entity()
export class MaterialConsumption {
  @PrimaryGeneratedColumn()
  id!: number;

  @ManyToOne(() => RawMaterial, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'rawMaterialId' })
  rawMaterial!: RawMaterial;

  @Column()
  rawMaterialId!: number;

  @Column()
  rawMaterialName!: string;

  // Snapshot of RawMaterial.unit at consumption time -- same reason as
  // MaterialBatch.rawMaterialUnit: names aren't unique (e.g. "Poly" piece vs
  // yard), so unit is what actually disambiguates which one this was.
  @Column({ nullable: true })
  rawMaterialUnit?: string;

  // Which batch this portion was drawn from -- kept for traceability. Can go
  // null if the batch itself is later deleted; the cost snapshot below still
  // holds, so historical totals stay correct either way.
  @ManyToOne(() => MaterialBatch, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'materialBatchId' })
  materialBatch?: MaterialBatch;

  @Column({ nullable: true })
  materialBatchId?: number;

  @Column('float')
  quantity!: number;

  @Column('float')
  unitCost!: number;

  // quantity * unitCost, stored at write time.
  @Column('float')
  totalCost!: number;

  @Column({ nullable: true })
  note?: string;

  @CreateDateColumn()
  consumedAt!: Date;
}
